apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-alerts
    receivers:
      - uid: discord-error-webhook
        type: discord
        settings:
          url: ${DISCORD_ERROR_WEBHOOK_URL}
          use_discord_username: false
        disableResolveMessage: false
